{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- $Project           := .Values.project }}
{{- $HlfDomain         := .Values.hlf_domain }}
{{- $IcaEndpoint       := .Values.ca.ca_endpoint }}
{{- $TlsCaEndpoint     := .Values.ca.tlsca_endpoint }}
{{- $IcaTlsCertFile    := .Values.ca.ica_tls_certfile | default "/tmp/ca-cert.pem" }}
{{- $TlsCaTlsCertFile  := .Values.ca.ica_tls_certfile | default "/tmp/tlsca-cert.pem" }}
{{- $ChannelName       := .Values.hlf_channel }}
{{- $BankName          := .Values.nameOverride }}
{{- $Msp_base_dir      := printf "%s%s" .Values.workdir "/peer/crypto/users" }}

{{- if .Values.fabric_actions.configure_org_channel | default false }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-ops.fullname" $ }}
  labels:
    {{- include "fabric-ops.labels" $ | nindent 4 }}
data:
{{- range .Values.organizatons }}
  configtx_{{ .name }}.yaml: |
      Organizations:
        - &{{ .name }}
          Name: {{ .name }}
          ID: {{ .name }}
          MSPDir: {{ .msp_dir | default "/crypto-config/peerOrganizations/msp" }}
          Policies:
            Readers:
              Type: Signature
              Rule: "OR('{{ .name }}.admin', '{{ .name }}.peer', '{{ .name }}.client')"
            Writers:
              Type: Signature
              Rule: "OR('{{ .name }}.admin', '{{ .name }}.client')"
            Admins:
              Type: Signature
              Rule: "OR('{{ .name }}.admin')"
            Endorsement:
              Type: Signature
              Rule: "OR('{{ .name }}.peer')"
          AnchorPeers:
            - Host: {{ .anchor_peer }}
              Port: {{ .anchor_peer_port }}
{{- end }}
  fabric_configure_org_channel.sh: |
      source /scripts/fabric_enroll.sh
      fabric_public_key_fetch {{ $IcaEndpoint }} {{ $IcaTlsCertFile }}
      fabric_public_key_fetch {{ $TlsCaEndpoint }} {{ $TlsCaTlsCertFile }}
      orderer_dir_setup
      {{- range .Values.admin_identity }}
          {{- if .ica_endpoint }}
      fabric_public_key_fetch {{ .ica_endpoint }} {{ .ica_tlscertfile }}
          {{- end }}
          {{- if .tlsca_endpoint }}
      fabric_public_key_fetch {{ .ica_endpoint }} {{ .tlsca_tlscertfile }}
          {{- end }}
      enroll \
        {{ .identity_name }} \
        {{ .identity_secret }} \
        {{ .identity_type }} \
        {{ .msp_base_dir | default $Msp_base_dir }} \
        {{ .ica_endpoint | default $IcaEndpoint }} \
        {{ .tlsca_endpoint | default $TlsCaEndpoint }} \
        {{ .ica_tlscertfile | default $IcaTlsCertFile }} \
        {{ .tlsca_tlscertfile | default $TlsCaTlsCertFile }} \
        {{ .hlf_domain | default $.Values.hlf_domain }} \
        {{ .require_msp_enrollment }} \
        {{ .require_tls_enrollment }}
      {{- end }}

      ORG_NAME=$1
      FABRIC_CA_URL=$2
      FABRIC_IDENTITY=$3
      FABRIC_IDENTITY_SECRET=$4
      FABRIC_IDENTITY_MSP_DIR=$5
      FABRIC_TLS_CERT_FILE=/tmp/$ORG_NAME-cert.pem

      fabric_public_key_fetch $FABRIC_CA_URL $FABRIC_TLS_CERT_FILE

      echo "============ Updating channel for $ORG_NAME ============"
      echo "------------------------------------"
      echo "Enrolling to ICA https://$FABRIC_CA_URL as $FABRIC_IDENTITY"
      echo "--------------------------------------------------------------------"
      while true; do
        fabric-ca-client enroll \
          {{- if .Values.debug_enroll }}
          --debug \
          {{- end }}
          --url https://$FABRIC_IDENTITY:$FABRIC_IDENTITY_SECRET@$FABRIC_CA_URL \
          --mspdir $FABRIC_IDENTITY_MSP_DIR \
          --csr.names O='{{ .Values.csr_names_o }}',L={{ .Values.csr_names_l }},ST={{ .Values.csr_names_st }},C={{ .Values.csr_names_cn }} \
          --tls.certfiles $FABRIC_TLS_CERT_FILE
        
        if [ $? -eq 0 ]; then
          mkdir $FABRIC_IDENTITY_MSP_DIR/tlscacerts
          cp -pr $FABRIC_IDENTITY_MSP_DIR/intermediatecerts/* $FABRIC_IDENTITY_MSP_DIR/intermediatecerts/ca-cert.pem
          cp -pr $FABRIC_IDENTITY_MSP_DIR/cacerts/* $FABRIC_IDENTITY_MSP_DIR/cacerts/ca-cert.pem      
          cp {{ $TlsCaTlsCertFile }} $FABRIC_IDENTITY_MSP_DIR/tlscacerts/ca.crt
          cp /tmp/config.yaml $FABRIC_IDENTITY_MSP_DIR/config.yaml
          echo "============ Displaying the msp dir directory $FABRIC_IDENTITY_MSP_DIR structure after rearrangements. ============"
          find $FABRIC_IDENTITY_MSP_DIR/ -type f
          break;
        else
          echo "============ Cannot login with the given identity $FABRIC_IDENTITY ============"
          rm -rf $FABRIC_IDENTITY_MSP_DIR/*
          sleep {{ .Values.retry_seconds  | default 10 }}
        fi
      done
           
      echo "============ Generating org material for $ORG_NAME ============"
      configtxgen -configPath {{ $.Values.workdir }}/peer -printOrg $ORG_NAME > $ORG_NAME.json
      echo "============ Fetching config block ============"
      peer channel fetch config config_block.pb -o {{ .Values.orderer_endpoint }} -c {{ $ChannelName }} --tls --cafile $ORDERER_CA --connTimeout {{ .Values.connTimeout }}
      echo "============ Converting the configuration to JSON ============"
      configtxlator proto_decode --input config_block.pb --type common.Block | jq .data.data[0].payload.data.config > config.json
      echo "============ Add the new Org $ORG_NAME crypto material ============"
      jq -s '.[0] * {"channel_group":{"groups":{"Application":{"groups": {"'${ORG_NAME}'":.[1]}}}}}' config.json $ORG_NAME.json > modified_config.json
      configtxlator proto_encode --input config.json --type common.Config --output config.pb
      configtxlator proto_encode --input modified_config.json --type common.Config --output modified_config.pb
      configtxlator compute_update --channel_id {{ $ChannelName }} --original config.pb --updated modified_config.pb --output org3_update.pb
      configtxlator proto_decode --input org3_update.pb --type common.ConfigUpdate | jq . > org3_update.json
      echo '{"payload":{"header":{"channel_header":{"channel_id":"{{ $ChannelName }}", "type":2}},"data":{"config_update":'$(cat org3_update.json)'}}}' | jq . > org3_update_in_envelope.json
      configtxlator proto_encode --input org3_update_in_envelope.json --type common.Envelope --output org3_update_in_envelope.pb
      echo "============ Signing the Channel Configuration Update ============"
      peer channel signconfigtx -f org3_update_in_envelope.pb --connTimeout {{ .Values.connTimeout }}
      echo "============ Updating Channel configuration ============"
      peer channel update -f org3_update_in_envelope.pb -c {{ $ChannelName }} -o {{ .Values.orderer_endpoint }} --tls --cafile $ORDERER_CA --connTimeout {{ .Values.connTimeout }}
      
      if [ $? -ne 0 ]; then
        echo "============ [ERROR] One of the previous step returned an error, please debug it manually using cli pod and re-run this job if necessary. ============"
      else
        echo "============ [SUCCESS] All steps have been executed successfully. ============"
      fi
  {{- end }}