# Copyright National Payments Corporation of India. All Rights Reserved.
# SPDX-License-Identifier:  GPL-3.0

workdir: /opt/gopath/src/github.com/hyperledger/fabric
peer_internal_service_port: "30002"
ttlSecondsAfterFinished: "100"
retry_seconds: 60
connTimeout: 60s
debug_enroll: false
tls_cert_file: /root/cert.pem
default_msp_dir: /tmp/fabric
filestore_ssl: false
# .Values.core_peer_mspconfigpath_override - Use only if your admin username is not "admin". 
# Not required for identity registration, but we use the same values file for deploying fabric-tools helm chart. 
# This must be under /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/
# Eg; /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/<admin-user>/msp
# core_peer_mspconfigpath_override: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/users/admin-org/msp
serviceAccount:
  # Specifies whether a service account should be created
  create: true
fabric_actions: 
 install_chaincode: false
 approve_chaincode: false
 create_channel: false
 commit_chaincode: false
 configure_org_channel: false
 update_anchor_peer: false

 image:
  repository: npcioss/hlf-builder
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.4"
ca:
 ca_endpoint: